`timescale 1ns / 1ps

// AXI4-Lite control wrapper for the HLS video scaler.
//
// This module contains no pixel-processing logic and no AXI4-Stream ports.
// It translates software register accesses into the discrete configuration
// signals consumed by the HLS core and exposes its status signals.
//
// Register map:
//   0x00 SCALER_CONTROL
//        bit  [0]:   requested_scale_enable
//        bits [2:1]: requested_resolution
//                    0 = VGA, 1 = 720p, 2 = 1080p, 3 = invalid
//        bits [4:3]: requested_aspect
//                    0 = crop; the remaining values are not implemented yet
//        bit  [5]:   requested_interpolation
//                    0 = nearest; bilinear is not implemented yet
//
//   0x04 SCALER_STATUS
//        bit  [0]:   active_scale_enable
//        bits [2:1]: active_resolution
//        bits [4:3]: active_aspect
//        bit  [5]:   active_interpolation
//        bit  [6]:   pending
module video_scaler_axi_control (
    input  wire        clk,
    input  wire        rst,

    // AXI4-Lite slave write-address channel.
    input  wire [3:0]  s_axi_awaddr,
    input  wire [2:0]  s_axi_awprot,
    input  wire        s_axi_awvalid,
    output reg         s_axi_awready,

    // AXI4-Lite slave write-data channel.
    input  wire [31:0] s_axi_wdata,
    input  wire [3:0]  s_axi_wstrb,
    input  wire        s_axi_wvalid,
    output reg         s_axi_wready,

    // AXI4-Lite slave write-response channel.
    output reg  [1:0]  s_axi_bresp,
    output reg         s_axi_bvalid,
    input  wire        s_axi_bready,

    // AXI4-Lite slave read-address channel.
    input  wire [3:0]  s_axi_araddr,
    input  wire [2:0]  s_axi_arprot,
    input  wire        s_axi_arvalid,
    output reg         s_axi_arready,

    // AXI4-Lite slave read-data channel.
    output reg  [31:0] s_axi_rdata,
    output reg  [1:0]  s_axi_rresp,
    output reg         s_axi_rvalid,
    input  wire        s_axi_rready,

    // Discrete configuration outputs toward the HLS core.
    output wire        requested_scale_enable,
    output wire [1:0]  requested_resolution,
    output wire [1:0]  requested_aspect,
    output wire        requested_interpolation,

    // Discrete status inputs generated by the HLS core.
    input  wire        active_scale_enable,
    input  wire [1:0]  active_resolution,
    input  wire [1:0]  active_aspect,
    input  wire        active_interpolation,
    input  wire        pending
);

    localparam [3:0] ADDR_SCALER_CONTROL = 4'h0;
    localparam [3:0] ADDR_SCALER_STATUS  = 4'h4;

    localparam [1:0] SCALER_RES_VGA   = 2'd0;
    localparam [1:0] SCALER_RES_720P  = 2'd1;
    localparam [1:0] SCALER_RES_1080P = 2'd2;

    localparam [1:0] SCALER_ASPECT_CROP = 2'd0;
    localparam       SCALER_NEAREST     = 1'b0;

    // AXI4-Lite allows AW and W to arrive independently and in either order.
    // Each half of the transaction is retained until both have been received.
    reg [3:0]  awaddr_reg;
    reg [31:0] wdata_reg;
    reg [3:0]  wstrb_reg;
    reg        aw_captured;
    reg        w_captured;

    // Registers that continuously drive the HLS discrete configuration ports.
    reg       requested_scale_enable_reg;
    reg [1:0] requested_resolution_reg;
    reg [1:0] requested_aspect_reg;
    reg       requested_interpolation_reg;

    wire control_value_valid;

    assign requested_scale_enable  = requested_scale_enable_reg;
    assign requested_resolution    = requested_resolution_reg;
    assign requested_aspect        = requested_aspect_reg;
    assign requested_interpolation = requested_interpolation_reg;

    // Only combinations implemented by the current HLS core are accepted.
    // Invalid writes still receive an AXI OKAY response, but leave the active
    // request register unchanged.
    assign control_value_valid =
        ((wdata_reg[2:1] == SCALER_RES_VGA)   ||
         (wdata_reg[2:1] == SCALER_RES_720P)  ||
         (wdata_reg[2:1] == SCALER_RES_1080P)) &&
        (wdata_reg[4:3] == SCALER_ASPECT_CROP) &&
        (wdata_reg[5]   == SCALER_NEAREST);

    // AXI4-Lite write transaction control.
    always @(posedge clk) begin
        if (rst) begin
            s_axi_awready <= 1'b1;
            s_axi_wready  <= 1'b1;
            s_axi_bresp   <= 2'b00;
            s_axi_bvalid  <= 1'b0;

            awaddr_reg  <= 4'd0;
            wdata_reg   <= 32'd0;
            wstrb_reg   <= 4'd0;
            aw_captured <= 1'b0;
            w_captured  <= 1'b0;
        end else begin
            if (s_axi_awready && s_axi_awvalid) begin
                awaddr_reg    <= s_axi_awaddr;
                aw_captured   <= 1'b1;
                s_axi_awready <= 1'b0;
            end

            if (s_axi_wready && s_axi_wvalid) begin
                wdata_reg    <= s_axi_wdata;
                wstrb_reg    <= s_axi_wstrb;
                w_captured   <= 1'b1;
                s_axi_wready <= 1'b0;
            end

            // A complete transaction exists once both independent channels
            // have been captured. A single OKAY response is then generated.
            if (aw_captured && w_captured) begin
                aw_captured  <= 1'b0;
                w_captured   <= 1'b0;
                s_axi_bresp  <= 2'b00;
                s_axi_bvalid <= 1'b1;
            end

            // No new write is accepted until software consumes the response.
            if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid  <= 1'b0;
                s_axi_awready <= 1'b1;
                s_axi_wready  <= 1'b1;
            end
        end
    end

    // Writable SCALER_CONTROL register.
    always @(posedge clk) begin
        if (rst) begin
            requested_scale_enable_reg  <= 1'b0;
            requested_resolution_reg    <= SCALER_RES_VGA;
            requested_aspect_reg        <= SCALER_ASPECT_CROP;
            requested_interpolation_reg <= SCALER_NEAREST;
        end else begin
            if (aw_captured && w_captured) begin
                case (awaddr_reg)
                    ADDR_SCALER_CONTROL: begin
                        // Every implemented field is contained in byte zero.
                        if (wstrb_reg[0] && control_value_valid) begin
                            requested_scale_enable_reg  <= wdata_reg[0];
                            requested_resolution_reg    <= wdata_reg[2:1];
                            requested_aspect_reg        <= wdata_reg[4:3];
                            requested_interpolation_reg <= wdata_reg[5];
                        end
                    end

                    default: begin
                        // Status and undefined addresses are read-only.
                    end
                endcase
            end
        end
    end

    // AXI4-Lite read transaction control. RDATA remains stable until the
    // processor performs the RVALID/RREADY handshake.
    always @(posedge clk) begin
        if (rst) begin
            s_axi_arready <= 1'b1;
            s_axi_rdata   <= 32'd0;
            s_axi_rresp   <= 2'b00;
            s_axi_rvalid  <= 1'b0;
        end else begin
            if (s_axi_arready && s_axi_arvalid) begin
                s_axi_arready <= 1'b0;
                s_axi_rresp   <= 2'b00;
                s_axi_rvalid  <= 1'b1;

                case (s_axi_araddr)
                    ADDR_SCALER_CONTROL:
                        s_axi_rdata <= {
                            26'd0,
                            requested_interpolation_reg,
                            requested_aspect_reg,
                            requested_resolution_reg,
                            requested_scale_enable_reg
                        };

                    ADDR_SCALER_STATUS:
                        s_axi_rdata <= {
                            25'd0,
                            pending,
                            active_interpolation,
                            active_aspect,
                            active_resolution,
                            active_scale_enable
                        };

                    default:
                        s_axi_rdata <= 32'd0;
                endcase
            end

            if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid  <= 1'b0;
                s_axi_arready <= 1'b1;
            end
        end
    end

endmodule
