`timescale 1ns / 1ps

// AXI4-Lite controlled wrapper for the AXI4-Stream Video source selector.
//
// Register map:
//   0x00 SOURCE_CONTROL
//        bit 0: requested_source (0 = TPG, 1 = camera)
//
//   0x04 SOURCE_STATUS
//        bit 0: active_source
//        bit 1: switch_pending
module source_selector_axi_wrapper #(
    parameter integer DATA_WIDTH = 24
)(
    input  wire                  clk,
    input  wire                  rst,

    // AXI4-Lite slave write-address channel.
    input  wire [3:0]            s_axi_awaddr,
    input  wire [2:0]            s_axi_awprot,
    input  wire                  s_axi_awvalid,
    output reg                   s_axi_awready,

    // AXI4-Lite slave write-data channel.
    input  wire [31:0]           s_axi_wdata,
    input  wire [3:0]            s_axi_wstrb,
    input  wire                  s_axi_wvalid,
    output reg                   s_axi_wready,

    // AXI4-Lite slave write-response channel.
    output reg  [1:0]            s_axi_bresp,
    output reg                   s_axi_bvalid,
    input  wire                  s_axi_bready,

    // AXI4-Lite slave read-address channel.
    input  wire [3:0]            s_axi_araddr,
    input  wire [2:0]            s_axi_arprot,
    input  wire                  s_axi_arvalid,
    output reg                   s_axi_arready,

    // AXI4-Lite slave read-data channel.
    output reg  [31:0]           s_axi_rdata,
    output reg  [1:0]            s_axi_rresp,
    output reg                   s_axi_rvalid,
    input  wire                  s_axi_rready,

    // AXI4-Stream Video input from the TPG.
    input  wire [DATA_WIDTH-1:0] s_axis_tpg_tdata,
    input  wire                  s_axis_tpg_tvalid,
    output wire                  s_axis_tpg_tready,
    input  wire                  s_axis_tpg_tuser,
    input  wire                  s_axis_tpg_tlast,

    // AXI4-Stream Video input from the camera.
    input  wire [DATA_WIDTH-1:0] s_axis_camera_tdata,
    input  wire                  s_axis_camera_tvalid,
    output wire                  s_axis_camera_tready,
    input  wire                  s_axis_camera_tuser,
    input  wire                  s_axis_camera_tlast,

    // Selected AXI4-Stream Video output toward the VDMA.
    output wire [DATA_WIDTH-1:0] m_axis_video_tdata,
    output wire                  m_axis_video_tvalid,
    input  wire                  m_axis_video_tready,
    output wire                  m_axis_video_tuser,
    output wire                  m_axis_video_tlast
);

    localparam [3:0] ADDR_SOURCE_CONTROL = 4'h0;
    localparam [3:0] ADDR_SOURCE_STATUS  = 4'h4;

    localparam SOURCE_TPG = 1'b0;

    // Address and data are captured independently because AXI4-Lite does not
    // require the AW and W channel handshakes to occur in the same cycle.
    reg [3:0]  awaddr_reg;
    reg [31:0] wdata_reg;
    reg [3:0]  wstrb_reg;
    reg        aw_captured;
    reg        w_captured;

    // Software request sent as a discrete signal to the selector core.
    reg requested_source_reg;

    // Status signals generated by the selector core.
    wire active_source;
    wire switch_pending;

    // AXI4-Lite write-channel control.
    always @(posedge clk) begin
        if (rst) begin
            s_axi_awready <= 1'b1;
            s_axi_wready  <= 1'b1;
            s_axi_bresp   <= 2'b00;
            s_axi_bvalid  <= 1'b0;

            awaddr_reg  <= 4'd0;
            wdata_reg   <= 32'd0;
            wstrb_reg   <= 4'd0;
            aw_captured <= 1'b0;
            w_captured  <= 1'b0;
        end else begin
            // Capture the write address when the AW handshake occurs.
            if (s_axi_awready && s_axi_awvalid) begin
                awaddr_reg    <= s_axi_awaddr;
                aw_captured   <= 1'b1;
                s_axi_awready <= 1'b0;
            end

            // Capture the write data independently from the address.
            if (s_axi_wready && s_axi_wvalid) begin
                wdata_reg    <= s_axi_wdata;
                wstrb_reg    <= s_axi_wstrb;
                w_captured   <= 1'b1;
                s_axi_wready <= 1'b0;
            end

            // Complete the write only after both independent channels have
            // delivered their information.
            if (aw_captured && w_captured) begin
                aw_captured  <= 1'b0;
                w_captured   <= 1'b0;
                s_axi_bresp  <= 2'b00;
                s_axi_bvalid <= 1'b1;
            end

            // Accept another write only after the master has received the
            // response from the previous transaction.
            if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid  <= 1'b0;
                s_axi_awready <= 1'b1;
                s_axi_wready  <= 1'b1;
            end
        end
    end

    // Writable selector control register.
    always @(posedge clk) begin
        if (rst) begin
            requested_source_reg <= SOURCE_TPG;
        end else begin
            // aw_captured and w_captured indicate that a complete AXI4-Lite
            // write has been assembled from the independent AW and W channels.
            if (aw_captured && w_captured) begin
                case (awaddr_reg)
                    ADDR_SOURCE_CONTROL: begin
                        // requested_source is located in byte zero, so the
                        // write is applied only when WSTRB[0] enables that byte.
                        if (wstrb_reg[0])
                            requested_source_reg <= wdata_reg[0];
                    end

                    default: begin
                        // Writes to the status or undefined addresses are
                        // acknowledged but do not modify any register.
                    end
                endcase
            end
        end
    end

    // AXI4-Lite read-channel control.
    //
    // RDATA is captured when the AR handshake occurs and remains stable until
    // the processor accepts it through the RVALID/RREADY handshake.
    always @(posedge clk) begin
        if (rst) begin
            s_axi_arready <= 1'b1;
            s_axi_rdata   <= 32'd0;
            s_axi_rresp   <= 2'b00;
            s_axi_rvalid  <= 1'b0;
        end else begin
            if (s_axi_arready && s_axi_arvalid) begin
                s_axi_arready <= 1'b0;
                s_axi_rresp   <= 2'b00;
                s_axi_rvalid  <= 1'b1;

                case (s_axi_araddr)
                    ADDR_SOURCE_CONTROL:
                        s_axi_rdata <= {
                            31'd0,
                            requested_source_reg
                        };

                    ADDR_SOURCE_STATUS:
                        s_axi_rdata <= {
                            30'd0,
                            switch_pending,
                            active_source
                        };

                    default:
                        s_axi_rdata <= 32'd0;
                endcase
            end

            // Rearm the address channel after the processor accepts RDATA.
            if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid  <= 1'b0;
                s_axi_arready <= 1'b1;
            end
        end
    end

    // The core receives only discrete configuration and status signals. It
    // remains independent of AXI4-Lite and can therefore be reused or tested
    // separately.
    source_selector_core #(
        .DATA_WIDTH(DATA_WIDTH)
    ) u_source_selector_core (
        .clk                    (clk),
        .rst                    (rst),
        .requested_source       (requested_source_reg),

        .s_axis_tpg_tdata       (s_axis_tpg_tdata),
        .s_axis_tpg_tvalid      (s_axis_tpg_tvalid),
        .s_axis_tpg_tready      (s_axis_tpg_tready),
        .s_axis_tpg_tuser       (s_axis_tpg_tuser),
        .s_axis_tpg_tlast       (s_axis_tpg_tlast),

        .s_axis_camera_tdata    (s_axis_camera_tdata),
        .s_axis_camera_tvalid   (s_axis_camera_tvalid),
        .s_axis_camera_tready   (s_axis_camera_tready),
        .s_axis_camera_tuser    (s_axis_camera_tuser),
        .s_axis_camera_tlast    (s_axis_camera_tlast),

        .m_axis_video_tdata     (m_axis_video_tdata),
        .m_axis_video_tvalid    (m_axis_video_tvalid),
        .m_axis_video_tready    (m_axis_video_tready),
        .m_axis_video_tuser     (m_axis_video_tuser),
        .m_axis_video_tlast     (m_axis_video_tlast),

        .active_source          (active_source),
        .switch_pending         (switch_pending)
    );

endmodule
