-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rgb_to_gray is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    pixel_in_V : IN STD_LOGIC_VECTOR (23 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of rgb_to_gray is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_4D : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001101";
    constant ap_const_lv16_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010010110";
    constant ap_const_lv14_1D : STD_LOGIC_VECTOR (13 downto 0) := "00000000011101";

    signal blue_V_fu_73_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal blue_V_reg_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ret_V_fu_81_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_reg_121 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_1_fu_91_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_1_reg_126 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_2_fu_100_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_2_reg_131 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_add_gray_stage_2_fu_40_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_add_gray_stage_2_fu_40_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call12 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call12 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call12 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call12 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp17 : BOOLEAN;
    signal grp_add_gray_stage_1_fu_46_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_add_gray_stage_1_fu_46_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call11 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call11 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call11 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call11 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp15 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal red_V_fu_53_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_fu_81_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal green_V_fu_63_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_1_fu_91_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_2_fu_100_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal pixel_in_V_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_1_fu_91_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_2_fu_100_p10 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_fu_81_p10 : STD_LOGIC_VECTOR (15 downto 0);

    component add_gray_stage_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        operand_a_V : IN STD_LOGIC_VECTOR (15 downto 0);
        operand_b_V : IN STD_LOGIC_VECTOR (13 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component add_gray_stage_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        operand_a_V : IN STD_LOGIC_VECTOR (15 downto 0);
        operand_b_V : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_add_gray_stage_2_fu_40 : component add_gray_stage_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        operand_a_V => grp_add_gray_stage_1_fu_46_ap_return,
        operand_b_V => ret_V_2_reg_131,
        ap_return => grp_add_gray_stage_2_fu_40_ap_return,
        ap_ce => grp_add_gray_stage_2_fu_40_ap_ce);

    grp_add_gray_stage_1_fu_46 : component add_gray_stage_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        operand_a_V => ret_V_reg_121,
        operand_b_V => ret_V_1_reg_126,
        ap_return => grp_add_gray_stage_1_fu_46_ap_return,
        ap_ce => grp_add_gray_stage_1_fu_46_ap_ce);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= grp_add_gray_stage_2_fu_40_ap_return(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                blue_V_reg_116 <= blue_V_fu_73_p1;
                ret_V_1_reg_126 <= ret_V_1_fu_91_p2;
                ret_V_2_reg_131 <= ret_V_2_fu_100_p2;
                ret_V_reg_121 <= ret_V_fu_81_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                pixel_in_V_int_reg <= pixel_in_V;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call12 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(grp_add_gray_stage_2_fu_40_ap_return, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= grp_add_gray_stage_2_fu_40_ap_return(15 downto 8);
        end if; 
    end process;

    blue_V_fu_73_p1 <= pixel_in_V_int_reg(8 - 1 downto 0);
    green_V_fu_63_p4 <= pixel_in_V_int_reg(15 downto 8);

    grp_add_gray_stage_1_fu_46_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp15, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp15) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_add_gray_stage_1_fu_46_ap_ce <= ap_const_logic_1;
        else 
            grp_add_gray_stage_1_fu_46_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_add_gray_stage_2_fu_40_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp17, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp17) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_add_gray_stage_2_fu_40_ap_ce <= ap_const_logic_1;
        else 
            grp_add_gray_stage_2_fu_40_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    red_V_fu_53_p4 <= pixel_in_V_int_reg(23 downto 16);
    ret_V_1_fu_91_p1 <= ret_V_1_fu_91_p10(8 - 1 downto 0);
    ret_V_1_fu_91_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(green_V_fu_63_p4),16));
    ret_V_1_fu_91_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv16_96) * unsigned(ret_V_1_fu_91_p1), 16));
    ret_V_2_fu_100_p1 <= ret_V_2_fu_100_p10(8 - 1 downto 0);
    ret_V_2_fu_100_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(blue_V_reg_116),14));
    ret_V_2_fu_100_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv14_1D) * unsigned(ret_V_2_fu_100_p1), 14));
    ret_V_fu_81_p1 <= ret_V_fu_81_p10(8 - 1 downto 0);
    ret_V_fu_81_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(red_V_fu_53_p4),16));
    ret_V_fu_81_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv16_4D) * unsigned(ret_V_fu_81_p1), 16));
end behav;
