// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module add_gray_stage_1 (
        ap_clk,
        ap_rst,
        operand_a_V,
        operand_b_V,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] operand_a_V;
input  [15:0] operand_b_V;
output  [15:0] ap_return;
input   ap_ce;

wire   [15:0] add_ln209_fu_28_p2;
reg   [15:0] add_ln209_reg_34;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        add_ln209_reg_34 <= add_ln209_fu_28_p2;
    end
end

assign add_ln209_fu_28_p2 = (operand_b_V + operand_a_V);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_return = add_ln209_reg_34;

endmodule //add_gray_stage_1
