// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rgb_to_gray (
        ap_clk,
        ap_rst,
        pixel_in_V,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [23:0] pixel_in_V;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

wire   [7:0] blue_V_fu_73_p1;
reg   [7:0] blue_V_reg_116;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [15:0] ret_V_fu_81_p2;
reg   [15:0] ret_V_reg_121;
wire   [15:0] ret_V_1_fu_91_p2;
reg   [15:0] ret_V_1_reg_126;
wire   [13:0] ret_V_2_fu_100_p2;
reg   [13:0] ret_V_2_reg_131;
wire   [15:0] grp_add_gray_stage_2_fu_40_ap_return;
reg    grp_add_gray_stage_2_fu_40_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call12;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call12;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call12;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call12;
wire    ap_block_pp0_stage0_11001_ignoreCallOp17;
wire   [15:0] grp_add_gray_stage_1_fu_46_ap_return;
reg    grp_add_gray_stage_1_fu_46_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call11;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call11;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call11;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call11;
wire    ap_block_pp0_stage0_11001_ignoreCallOp15;
wire    ap_block_pp0_stage0;
wire   [7:0] red_V_fu_53_p4;
wire   [7:0] ret_V_fu_81_p1;
wire   [7:0] green_V_fu_63_p4;
wire   [7:0] ret_V_1_fu_91_p1;
wire   [7:0] ret_V_2_fu_100_p1;
reg    ap_ce_reg;
reg   [23:0] pixel_in_V_int_reg;
reg   [7:0] ap_return_int_reg;
wire   [15:0] ret_V_1_fu_91_p10;
wire   [13:0] ret_V_2_fu_100_p10;
wire   [15:0] ret_V_fu_81_p10;

add_gray_stage_2 grp_add_gray_stage_2_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .operand_a_V(grp_add_gray_stage_1_fu_46_ap_return),
    .operand_b_V(ret_V_2_reg_131),
    .ap_return(grp_add_gray_stage_2_fu_40_ap_return),
    .ap_ce(grp_add_gray_stage_2_fu_40_ap_ce)
);

add_gray_stage_1 grp_add_gray_stage_1_fu_46(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .operand_a_V(ret_V_reg_121),
    .operand_b_V(ret_V_1_reg_126),
    .ap_return(grp_add_gray_stage_1_fu_46_ap_return),
    .ap_ce(grp_add_gray_stage_1_fu_46_ap_ce)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= {{grp_add_gray_stage_2_fu_40_ap_return[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        blue_V_reg_116 <= blue_V_fu_73_p1;
        ret_V_1_reg_126 <= ret_V_1_fu_91_p2;
        ret_V_2_reg_131 <= ret_V_2_fu_100_p2;
        ret_V_reg_121 <= ret_V_fu_81_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        pixel_in_V_int_reg <= pixel_in_V;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = {{grp_add_gray_stage_2_fu_40_ap_return[15:8]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp15) & (1'b1 == ap_ce_reg))) begin
        grp_add_gray_stage_1_fu_46_ap_ce = 1'b1;
    end else begin
        grp_add_gray_stage_1_fu_46_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp17) & (1'b1 == ap_ce_reg))) begin
        grp_add_gray_stage_2_fu_40_ap_ce = 1'b1;
    end else begin
        grp_add_gray_stage_2_fu_40_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp17 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call12 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call11 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call12 = ~(1'b1 == 1'b1);

assign blue_V_fu_73_p1 = pixel_in_V_int_reg[7:0];

assign green_V_fu_63_p4 = {{pixel_in_V_int_reg[15:8]}};

assign red_V_fu_53_p4 = {{pixel_in_V_int_reg[23:16]}};

assign ret_V_1_fu_91_p1 = ret_V_1_fu_91_p10;

assign ret_V_1_fu_91_p10 = green_V_fu_63_p4;

assign ret_V_1_fu_91_p2 = (16'd150 * ret_V_1_fu_91_p1);

assign ret_V_2_fu_100_p1 = ret_V_2_fu_100_p10;

assign ret_V_2_fu_100_p10 = blue_V_reg_116;

assign ret_V_2_fu_100_p2 = (14'd29 * ret_V_2_fu_100_p1);

assign ret_V_fu_81_p1 = ret_V_fu_81_p10;

assign ret_V_fu_81_p10 = red_V_fu_53_p4;

assign ret_V_fu_81_p2 = (16'd77 * ret_V_fu_81_p1);

endmodule //rgb_to_gray
