`timescale 1ns / 1ps

// AXI4-Lite control wrapper for the HLS video filter.
//
// This module deliberately contains no pixel-processing logic and no
// AXI4-Stream ports. It only translates software register transactions into
// the discrete configuration signal consumed by the HLS core and exposes the
// status signals generated by that core.
//
// Register map:
//   0x00 FILTER_CONTROL
//        bits [1:0]: requested_mode
//                    0 = bypass
//                    1 = grayscale
//                    2 = Sobel
//                    3 = invalid, write ignored
//
//   0x04 FILTER_STATUS
//        bits [1:0]: active_mode
//        bit  [2]:   pending
module video_filter_axi_control (
    input  wire        clk,
    input  wire        rst,

    // AXI4-Lite slave write-address channel.
    input  wire [3:0]  s_axi_awaddr,
    input  wire [2:0]  s_axi_awprot,
    input  wire        s_axi_awvalid,
    output reg         s_axi_awready,

    // AXI4-Lite slave write-data channel.
    input  wire [31:0] s_axi_wdata,
    input  wire [3:0]  s_axi_wstrb,
    input  wire        s_axi_wvalid,
    output reg         s_axi_wready,

    // AXI4-Lite slave write-response channel.
    output reg  [1:0]  s_axi_bresp,
    output reg         s_axi_bvalid,
    input  wire        s_axi_bready,

    // AXI4-Lite slave read-address channel.
    input  wire [3:0]  s_axi_araddr,
    input  wire [2:0]  s_axi_arprot,
    input  wire        s_axi_arvalid,
    output reg         s_axi_arready,

    // AXI4-Lite slave read-data channel.
    output reg  [31:0] s_axi_rdata,
    output reg  [1:0]  s_axi_rresp,
    output reg         s_axi_rvalid,
    input  wire        s_axi_rready,

    // Discrete configuration output toward the HLS core.
    output wire [1:0]  requested_mode,

    // Discrete status inputs generated by the HLS core.
    input  wire [1:0]  active_mode,
    input  wire        pending
);

    localparam [3:0] ADDR_FILTER_CONTROL = 4'h0;
    localparam [3:0] ADDR_FILTER_STATUS  = 4'h4;

    localparam [1:0] FILTER_BYPASS    = 2'd0;
    localparam [1:0] FILTER_GRAYSCALE = 2'd1;
    localparam [1:0] FILTER_SOBEL     = 2'd2;

    // AXI4-Lite permits the write address and write data to arrive in
    // different cycles and in either order. Each channel is therefore
    // captured independently until both halves of the write are available.
    reg [3:0]  awaddr_reg;
    reg [31:0] wdata_reg;
    reg [3:0]  wstrb_reg;
    reg        aw_captured;
    reg        w_captured;

    // Register that continuously drives the discrete HLS configuration port.
    reg [1:0] requested_mode_reg;

    assign requested_mode = requested_mode_reg;

    // AXI4-Lite write transaction control.
    always @(posedge clk) begin
        if (rst) begin
            s_axi_awready <= 1'b1;
            s_axi_wready  <= 1'b1;
            s_axi_bresp   <= 2'b00;
            s_axi_bvalid  <= 1'b0;

            awaddr_reg  <= 4'd0;
            wdata_reg   <= 32'd0;
            wstrb_reg   <= 4'd0;
            aw_captured <= 1'b0;
            w_captured  <= 1'b0;
        end else begin
            // Capture AW only when both VALID and READY are asserted.
            if (s_axi_awready && s_axi_awvalid) begin
                awaddr_reg    <= s_axi_awaddr;
                aw_captured   <= 1'b1;
                s_axi_awready <= 1'b0;
            end

            // Capture W independently from AW.
            if (s_axi_wready && s_axi_wvalid) begin
                wdata_reg    <= s_axi_wdata;
                wstrb_reg    <= s_axi_wstrb;
                w_captured   <= 1'b1;
                s_axi_wready <= 1'b0;
            end

            // Once both channels have been captured, acknowledge exactly one
            // complete write transaction with an OKAY response.
            if (aw_captured && w_captured) begin
                aw_captured  <= 1'b0;
                w_captured   <= 1'b0;
                s_axi_bresp  <= 2'b00;
                s_axi_bvalid <= 1'b1;
            end

            // A new write is accepted only after the previous response has
            // completed its BVALID/BREADY handshake.
            if (s_axi_bvalid && s_axi_bready) begin
                s_axi_bvalid  <= 1'b0;
                s_axi_awready <= 1'b1;
                s_axi_wready  <= 1'b1;
            end
        end
    end

    // Writable FILTER_CONTROL register.
    always @(posedge clk) begin
        if (rst) begin
            requested_mode_reg <= FILTER_BYPASS;
        end else begin
            // This condition is true for one cycle when a complete write has
            // been assembled from the independent AW and W channels.
            if (aw_captured && w_captured) begin
                case (awaddr_reg)
                    ADDR_FILTER_CONTROL: begin
                        // The mode occupies byte zero, so WSTRB[0] must enable
                        // that byte before the register may be modified.
                        if (wstrb_reg[0]) begin
                            case (wdata_reg[1:0])
                                FILTER_BYPASS,
                                FILTER_GRAYSCALE,
                                FILTER_SOBEL:
                                    requested_mode_reg <= wdata_reg[1:0];

                                default: begin
                                    // Mode 3 is not implemented. The AXI write
                                    // is acknowledged, but configuration is
                                    // intentionally left unchanged.
                                end
                            endcase
                        end
                    end

                    default: begin
                        // Writes to FILTER_STATUS or undefined addresses are
                        // acknowledged without changing any register.
                    end
                endcase
            end
        end
    end

    // AXI4-Lite read transaction control.
    //
    // RDATA is sampled when the AR handshake occurs and remains stable until
    // the processor completes the RVALID/RREADY handshake.
    always @(posedge clk) begin
        if (rst) begin
            s_axi_arready <= 1'b1;
            s_axi_rdata   <= 32'd0;
            s_axi_rresp   <= 2'b00;
            s_axi_rvalid  <= 1'b0;
        end else begin
            if (s_axi_arready && s_axi_arvalid) begin
                s_axi_arready <= 1'b0;
                s_axi_rresp   <= 2'b00;
                s_axi_rvalid  <= 1'b1;

                case (s_axi_araddr)
                    ADDR_FILTER_CONTROL:
                        s_axi_rdata <= {
                            30'd0,
                            requested_mode_reg
                        };

                    ADDR_FILTER_STATUS:
                        s_axi_rdata <= {
                            29'd0,
                            pending,
                            active_mode
                        };

                    default:
                        s_axi_rdata <= 32'd0;
                endcase
            end

            // Rearm AR only after software has accepted the current RDATA.
            if (s_axi_rvalid && s_axi_rready) begin
                s_axi_rvalid  <= 1'b0;
                s_axi_arready <= 1'b1;
            end
        end
    end

endmodule
